--vim.g.loaded_netrw = 1
--vim.g.loaded_netrwPlugin = 1
--
---- set termguicolors to enable highlight groups
--vim.opt.termguicolors = true
--
--local function on_attach(bufnr)
--    local api = require('nvim-tree.api')
--    api.config.mappings.default_on_attach(bufnr)
--    vim.keymap.del('n', 's', { buffer = bufnr })
--end
--
---- OR setup with some options
--require("nvim-tree").setup({
--    sort = {
--        sorter = "case_sensitive",
--    },
--    view = {
--        width = 30,
--    },
--    renderer = {
--        group_empty = true,
--    },
--    update_focused_file = {
--        enable = true,
--        update_cwd = true,
--    },
--    system_open = {
--        cmd = "",
--    },
--    on_attach = on_attach
--})
