general.import = ["./colorscheme.toml"]

[font]
size = 20

[keyboard]
bindings = [
    # Tmux leader
    { chars = "\u0002", key = "S", mods = "Command" },
    { chars = "\u001B\u007F", key = "Back", mods = "Alt" },
    { chars = "\u0015", key = "Back", mods = "Command" },
]

[window]
decorations = "none"
startup_mode = "Maximized"
